apiVersion: v1
kind: Pod
metadata:
  name: backend
spec:
  containers:
    - name: mysql
      image: mysql
      ports:
        - containerPort: 3306
  tolerations:
  - key: spray
    value: mortein
    effect: NoSchedule
    operator: Equal
