apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  ports:
  - nodePort: 30082 #will give you a random 3XXXX port
    port: 80
    targetPort: 80
  selector:
          label: nginx-label
  type: NodePort
