apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-label
  template:
    metadata:
      labels:
        app: nginx-label
    spec:
      containers:
      - name: ninx-cont
        image: nginx
        ports:
                - containerPort: 80        
