apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-name
  labels:
    failure-domain.beta.kubernetes.io/zone: eu-west-1c
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk: # GCP volume parameters
    pvcName: pvc-name 
    fsType: ext4 # Filesystem type of the volume