apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-name
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow # class name of the storage
  mountOptions:
    - hard
    - nfsvers=4.0
  nfs:
    path: /path/to/nfs/volume
    server: nfs-server-ip-address